=== trezor/trezor-suite/suite-common/message-system/schema/config.schema.v1.json
{
    "$id": "https://data.trezor.io/message-system/schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Message system",
    "description": "JSON schema of the Trezor Suite messaging system.",
    "type": "object",
    "required": ["version", "timestamp", "sequence", "actions"],
    "properties": {
        "version": {
            "description": "A version of the messaging system. In case we would change the format of the config itself.",
            "type": "integer",
            "minimum": 1,
            "default": 1
        },
        "timestamp": {
            "$ref": "#/definitions/date-time"
        },
        "sequence": {
            "description": "An increasing counter. Trezor Suite must decline any sequence lower than the latest number. This is to protect against replay attacks, where an attacker could send an older version of the file, and Trezor Suite would accept it.",
            "type": "integer",
            "minimum": 1,
            "default": 1
        },
        "actions": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "title": "Action",
                "type": "object",
                "required": ["conditions", "message"],
                "properties": {
                    "conditions": {
                        "type": "array",
                        "items": {
                            "title": "Condition",
                            "type": "object",
                            "properties": {
                                "duration": {
                                    "title": "Duration",
                                    "type": "object",
                                    "required": ["from", "to"],
                                    "properties": {
                                        "from": {
                                            "$ref": "#/definitions/date-time"
                                        },
                                        "to": {
                                            "$ref": "#/definitions/date-time"
                                        }
                                    },
                                    "additionalProperties": false
                                },
                                "os": {
                                    "title": "Operating System",
                                    "type": "object",
                                    "required": [
                                        "macos",
                                        "linux",
                                        "windows",
                                        "android",
                                        "ios",
                                        "chromeos"
                                    ],
                                    "properties": {
                                        "macos": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "linux": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "windows": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "android": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "ios": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "chromeos": {
                                            "$ref": "#/definitions/version"
                                        }
                                    },
                                    "additionalProperties": {
                                        "$ref": "#/definitions/version"
                                    }
                                },
                                "environment": {
                                    "title": "Environment",
                                    "type": "object",
                                    "required": ["desktop", "mobile", "web"],
                                    "properties": {
                                        "desktop": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "mobile": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "web": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "revision": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "browser": {
                                    "title": "Browser",
                                    "type": "object",
                                    "required": ["firefox", "chrome", "chromium"],
                                    "properties": {
                                        "firefox": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "chrome": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "chromium": {
                                            "$ref": "#/definitions/version"
                                        }
                                    },
                                    "additionalProperties": {
                                        "$ref": "#/definitions/version"
                                    }
                                },
                                "transport": {
                                    "title": "Transport",
                                    "type": "object",
                                    "required": ["bridge", "webusbplugin"],
                                    "properties": {
                                        "bridge": {
                                            "$ref": "#/definitions/version"
                                        },
                                        "webusbplugin": {
                                            "$ref": "#/definitions/version"
                                        }
                                    },
                                    "additionalProperties": {
                                        "$ref": "#/definitions/version"
                                    }
                                },
                                "settings": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {
                                        "title": "Settings",
                                        "description": "If a setting is not specified, then it can be either true or false. Currently, 'tor' and coin symbols are supported.",
                                        "type": "object",
                                        "properties": {
                                            "tor": {
                                                "type": "boolean"
                                            }
                                        },
                                        "additionalProperties": true
                                    }
                                },
                                "devices": {
                                    "type": "array",
                                    "items": {
                                        "title": "Device",
                                        "type": "object",
                                        "required": [
                                            "model",
                                            "firmwareRevision",
                                            "firmware",
                                            "bootloader",
                                            "variant",
                                            "vendor"
                                        ],
                                        "properties": {
                                            "model": {
                                                "title": "Model",
                                                "type": "string",
                                                "enum": [
                                                    "1",
                                                    "T",
                                                    "T1B1",
                                                    "T2T1",
                                                    "T2B1",
                                                    "Safe 3",
                                                    ""
                                                ]
                                            },
                                            "firmwareRevision": {
                                                "title": "Firmware Revision",
                                                "type": "string"
                                            },
                                            "firmware": {
                                                "$ref": "#/definitions/version"
                                            },
                                            "bootloader": {
                                                "$ref": "#/definitions/version"
                                            },
                                            "variant": {
                                                "title": "Firmware Variant",
                                                "type": "string",
                                                "enum": ["*", "bitcoin-only", "regular"]
                                            },
                                            "vendor": {
                                                "title": "Vendor",
                                                "description": "Eligible authorized vendors.",
                                                "type": "string",
                                                "enum": ["*", "trezor.io"]
                                            }
                                        },
                                        "additionalProperties": false
                                    }
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "message": {
                        "title": "Message",
                        "type": "object",
                        "required": [
                            "id",
                            "priority",
                            "dismissible",
                            "variant",
                            "category",
                            "content"
                        ],
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "priority": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 100
                            },
                            "dismissible": {
                                "type": "boolean"
                            },
                            "variant": {
                                "title": "Variant",
                                "type": "string",
                                "enum": ["info", "warning", "critical"]
                            },
                            "category": {
                                "oneOf": [
                                    {
                                        "$ref": "#/definitions/category"
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/definitions/category"
                                        }
                                    }
                                ]
                            },
                            "content": {
                                "$ref": "#/definitions/localization"
                            },
                            "cta": {
                                "title": "CTA",
                                "description": "Only used for 'banner' and 'context' categories.",
                                "required": ["action", "link", "label"],
                                "type": "object",
                                "properties": {
                                    "action": {
                                        "type": "string",
                                        "enum": ["internal-link", "external-link"]
                                    },
                                    "link": {
                                        "type": "string"
                                    },
                                    "anchor": {
                                        "type": "string"
                                    },
                                    "label": {
                                        "$ref": "#/definitions/localization"
                                    }
                                },
                                "additionalProperties": false
                            },
                            "modal": {
                                "title": "Modal",
                                "type": "object",
                                "description": "Only used for 'modal' category.",
                                "required": ["title", "image"],
                                "properties": {
                                    "title": {
                                        "$ref": "#/definitions/localization"
                                    },
                                    "image": {
                                        "type": "string"
                                    }
                                },
                                "additionalProperties": false
                            },
                            "feature": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "title": "Feature",
                                    "description": "Only used for 'feature' category. Feature flag can disable a feature for a specific version of a specific app.",
                                    "type": "object",
                                    "required": ["domain", "flag"],
                                    "properties": {
                                        "domain": {
                                            "type": "string"
                                        },
                                        "flag": {
                                            "type": "boolean"
                                        },
                                        "isPublic": {
                                            "type": "boolean"
                                        }
                                    },
                                    "additionalProperties": true
                                }
                            },
                            "context": {
                                "title": "Context",
                                "type": "object",
                                "description": "Only used for 'context' category.",
                                "required": ["domain"],
                                "properties": {
                                    "domain": {
                                        "description": "The domain to which the message applies. Only used for 'context' category.",
                                        "oneOf": [
                                            {
                                                "type": "string"
                                            },
                                            {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        ]
                                    }
                                },
                                "additionalProperties": false
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false,
    "definitions": {
        "version": {
            "examples": ["<=20.01", ">30", "~20.1", "^20.1", "82", "*", "!", ["<70", ">71"]],
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ]
        },
        "localization": {
            "title": "Localization",
            "description": "A multilingual text localization.",
            "type": "object",
            "required": ["en-GB", "en", "es", "cs", "ru", "ja", "fr"],
            "properties": {
                "en-GB": {
                    "type": "string"
                },
                "en": {
                    "type": "string"
                },
                "es": {
                    "type": "string"
                },
                "cs": {
                    "type": "string"
                },
                "ru": {
                    "type": "string"
                },
                "ja": {
                    "type": "string"
                },
                "fr": {
                    "type": "string"
                }
            },
            "additionalProperties": {
                "type": "string"
            }
        },
        "category": {
            "type": "string",
            "enum": ["banner", "context", "modal", "feature"]
        },
        "date-time": {
            "description": "ISO 8601 date-time format.",
            "type": "string",
            "examples": ["2021-03-03T03:48:16+00:00", "2021-03-03T03:48:16Z"]
        }
    }
}

=== trezor/trezor-suite/suite-common/message-system/config/config.v1.json
{
    "version": 1,
    "timestamp": "2023-12-05T00:00:00+00:00",
    "sequence": 47,
    "actions": [
        {
            "conditions": [
                {
                    "environment": {
                        "desktop": "23.10.1",
                        "mobile": "!",
                        "web": "23.10.1"
                    },
                    "devices": [
                        {
                            "model": "T2B1",
                            "firmware": "*",
                            "bootloader": "*",
                            "variant": "*",
                            "firmwareRevision": "*",
                            "vendor": "*"
                        }
                    ]
                }
            ],
            "message": {
                "id": "8231c0f4-e778-4838-bc40-5c28d8832f06",
                "priority": 93,
                "dismissible": false,
                "variant": "critical",
                "category": "banner",
                "content": {
                    "en-GB": "Essential update of Trezor Suite is required for your new Trezor Safe 3.",
                    "en": "Essential update of Trezor Suite is required for your new Trezor Safe 3.",
                    "es": "Es necesario que actualices Trezor Suite para tu nuevo Trezor Safe 3.",
                    "cs": "Pro nový Trezor Safe 3 je nutná aktualizace Trezor Suite.",
                    "ru": "Для нового Trezor Safe 3 требуется обновление Trezor Suite.",
                    "ja": "新しいTrezor Safe 3を使用するには、Trezor Suiteの必須アップデートが必要です。",
                    "hu": "A Trezor Suite alapvető frissítése szükséges az új Trezor Safe 3 készülékhez.",
                    "it": "Per il nuovo Trezor Safe 3 è necessario un aggiornamento essenziale di Trezor Suite.",
                    "fr": "Une mise à jour essentielle de Trezor Suite est nécessaire pour votre nouveau portefeuille Trezor Safe 3.",
                    "de": "Für deinen neuen Trezor Safe 3 ist ein wichtiges Update der Trezor Suite erforderlich."
                },
                "cta": {
                    "action": "internal-link",
                    "link": "settings-index",
                    "anchor": "@general-settings/version-with-update",
                    "label": {
                        "en-GB": "Update Suite",
                        "en": "Update Suite",
                        "es": "Actualizar Suite",
                        "cs": "Aktualizovat Suite",
                        "ru": "Обновить Suite",
                        "ja": "Suiteのアップデート",
                        "hu": "Frissítés Suite",
                        "it": "Suite di aggiornamento",
                        "fr": "Mettre à jour Suite",
                        "de": "Suite aktualisieren"
                    }
                }
            }
        },
        {
            "conditions": [
                {
                    "environment": {
                        "desktop": ">23.10.1",
                        "mobile": "!",
                        "web": ">23.10.1"
                    },
                    "devices": [
                        {
                            "model": "T2B1",
                            "firmware": "<2.6.3",
                            "bootloader": "*",
                            "variant": "*",
                            "firmwareRevision": "*",
                            "vendor": "*"
                        }
                    ]
                }
            ],
            "message": {
                "id": "e11a586f-f2d7-4c7b-7dd9-d8f56d1c90ad",
                "priority": 92,
                "dismissible": false,
                "variant": "critical",
                "category": "banner",
                "content": {
                    "en-GB": "An update is available for your Trezor device. Make sure you’ve got your recovery seed ready as you’ll need it to regain access to your coins.",
                    "en": "An update is available for your Trezor device. Make sure you’ve got your recovery seed ready as you’ll need it to regain access to your coins.",
                    "es": "Hay una actualización disponible para tu dispositivo Trezor. Asegúrate de que la semilla de recuperación está lista, ya que la necesitarás para recuperar el acceso a tus monedas.",
                    "cs": "Pro zařízení Trezor je k dispozici aktualizace. Ujistěte se, že máte připravený recovery seed, protože jej budete potřebovat k obnovení přístupu k mincím.",
                    "ru": "Для устройства Trezor доступно обновление. Убедитесь, что у вас наготове семена восстановления, поскольку они понадобятся для восстановления доступа к монетам.",
                    "ja": "お使いのTrezorデバイスにアップデートが提供されています。コインへのアクセスを回復するにはリカバリーのシードが必要です。",
                    "hu": "Frissítés érhető el a Trezor készülékéhez. Győződjön meg róla, hogy készenlétben tartja a helyreállítási magot, mivel szüksége lesz rá, hogy újra hozzáférjen az érméihez.",
                    "it": "È disponibile un aggiornamento per il vostro dispositivo Trezor. Assicuratevi di avere pronto il seme di ripristino, che vi servirà per riavere accesso alle monete.",
                    "fr": "Une mise à jour est disponible pour votre dispositif Trezor. Assurez-vous d’avoir votre seed de récupération à portée de main, car vous en aurez besoin pour accéder à nouveau à vos coins.",
                    "de": "Es gibt ein Update für dein Trezor Gerät. Halte deinen Recovery Seed bereit. Du brauchst ihn, um wieder auf deine Coins zuzugreifen."
                },
                "cta": {
                    "action": "internal-link",
                    "link": "firmware-index",
                    "label": {
                        "en-GB": "Update now",
                        "en": "Update now",
                        "es": "Actualizar ahora",
                        "cs": "Aktualizovat teď",
                        "ru": "Обновить сейчас",
                        "ja": "今すぐアップデート",
                        "hu": "Frissítés most",
                        "it": "Aggiorna ora",
                        "fr": "Mettre à jour maintenant",
                        "de": "Jetzt aktualisieren"
                    }
                }
            }
        },
        {
            "conditions": [
                {
                    "devices": [
                        {
                            "model": "T",
                            "firmware": "<2.6.0",
                            "bootloader": "*",
                            "variant": "*",
                            "firmwareRevision": "*",
                            "vendor": "*"
                        },
                        {
                            "model": "T2T1",
                            "firmware": "<2.6.0",
                            "bootloader": "*",
                            "variant": "*",
                            "firmwareRevision": "*",
                            "vendor": "*"
                        },
                        {
                            "model": "1",
                            "firmware": "<1.12.1",
                            "bootloader": "*",
                            "variant": "*",
                            "firmwareRevision": "*",
                            "vendor": "*"
                        },
                        {
                            "model": "T1B1",
                            "firmware": "<1.12.1",
                            "bootloader": "*",
                            "variant": "*",
                            "firmwareRevision": "*",
                            "vendor": "*"
                        }
                    ],
                    "environment": {
                        "desktop": ">=23.1.0",
                        "mobile": "!",
                        "web": "!"
                    }
                }
            ],
            "message": {
                "id": "6f793f82-5e13-492f-803c-2d5Fsdcc3cb6",
                "priority": 92,
                "dismissible": true,
                "variant": "warning",
                "category": ["context", "feature"],
                "content": {
                    "en-GB": "Firmware update required to enable the coinjoin feature",
                    "en": "Firmware update required to enable the coinjoin feature.",
                    "es": "Se requiera una actualización del firmware para habilitar la función CoinJoin.",
                    "cs": "Aktualizujte prosím firmware, abyste mohli používat funkci coinjoin.",
                    "ru": "Пожалуйста, обновите прошивку, чтобы иметь возможность использовать функцию coinjoin",
                    "ja": "コインジョイン機能を使用できるようにファームウェアをアップデートしてください。",
                    "hu": "Firmware-frissítés szükséges a coinjoin funkció engedélyezéséhez",
                    "it": "Aggiornamento del firmware necessario per abilitare la funzione coinjoin",
                    "fr": "Mise à jour du micrologiciel nécessaire pour activer la fonctionnalité Coinjoin",
                    "de": "Firmware-Update erforderlich, um CoinJoin zu aktivieren"
                },
                "context": { "domain": "accounts.coinjoin" },
                "feature": [
                    {
                        "domain": "coinjoin",
                        "flag": false
                    }
                ]
            }
        },
        {
            "conditions": [
                {
                    "environment": {
                        "desktop": ">=23.8.1",
                        "mobile": "!",
                        "web": ">=23.8.1"
                    }
                }
            ],
            "message": {
                "id": "cdkf9j02-b796-4c67-abcb-ac38c15ae343",
                "priority": 90,
                "dismissible": false,
                "variant": "info",
                "category": ["feature"],
